services:
  library:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - "8080"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=test123456
      - POSTGRES_USER=library
    ports:
      - 5432:5432
    expose:
      - "5432"
