services:
  library:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - HIBERNATE_DDL_AUTO=${HIBERNATE_DDL_AUTO}
    depends_on:
      - db
    networks:
      - applicationNetwork
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - applicationNetwork

networks:
  applicationNetwork:
    name: applicationNetwork
