services:
  library:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - dbUser=${dbUser}
      - dbPassword=${dbPassword}
      - dbPort=${dbPort}
      - hibernateDdlAuto=${hibernateDdlAuto}
    depends_on:
      - db
    networks:
      - applicationNetwork
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${dbPassword}
      - POSTGRES_USER=${dbUser}
    ports:
      - ${dbPort}:${dbPort}
    networks:
      - applicationNetwork

networks:
  applicationNetwork:
    name: applicationNetwork
